// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evoogvazubdyjapdzvpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2b29ndmF6dWJkeWphcGR6dnB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwODY3NTMsImV4cCI6MjA2MjY2Mjc1M30.-PFFMdqhnLW9tTTsYdWdEG0sbqWMr_8s36qYLVfGFM4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);